# Generated by Django 4.1.5 on 2023-01-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=20)),
                ('follow_count', models.PositiveIntegerField(verbose_name='Переходов')),
            ],
        ),
    ]
