# Generated by Django 4.1.5 on 2023-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='follow_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Переходов'),
        ),
    ]
